version: "3"
services:
    nginx:
        container_name: nginx
        image: nginx:1.18.0-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./domains:/var/www
#            - ./ssl:/etc/nginx/ssl
            - ./nginx/:/etc/nginx/conf.d/
#            - ./certbot/conf:/etc/nginx/ssl
#            - ./certbot/www:/var/www/certbot
        depends_on:
            - php-fpm
        network_mode: "host"
    php-fpm:
        container_name: php-fpm
        user: "1000:1000"
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./domains:/var/www
        network_mode: "host"

#    certbot:
#        container_name: certbot
        # image: certbot/certbot
        # volumes:
        #     - ./certbot/conf:/etc/letsencrypt
        #     - ./certbot/logs:/var/log/letsencrypt
        #     - ./certbot/www:/var/www/certbot
        # depends_on: 
        #     - nginx
 
